/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ff631f2f29a6942ca7aa426ba156cabe)
interface __BaseEnv_CloudflareEnv {
	WORKSPACE_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	OIDC_ISSUER: "https://identity.dopedb.dev";
	OIDC_AUDIENCE: "https://iam.googleapis.com";
	OIDC_ACCOUNT_ID: "0af3820c996f277b2f17ee446d03f60a";
	OIDC_WORKLOAD_ID: "e9cdd314-e94a-4827-9777-ec4068daf494";
	OIDC_SUBJECT: "dopedb:workspace:production";
	WORKSPACE_RUNTIME: "cloudflare";
	PRODUCT_ANALYTICS: Fetcher /* dopedb-product-analytics */;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	WORKLOAD_IDENTITY: Service /* entrypoint WorkspaceIdentity from dopedb-workspace-identity */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OIDC_ISSUER" | "OIDC_AUDIENCE" | "OIDC_ACCOUNT_ID" | "OIDC_WORKLOAD_ID" | "OIDC_SUBJECT" | "WORKSPACE_RUNTIME">> {}
}
