export const articleSharingCopy = {
  en: {
    invitation: "Article invitation", open: "Open shared Article", unavailable: "This link is unavailable for this account",
    unavailableBody: "Sign in with the email the sender invited. The invitation may have expired, been cancelled, or lost its permissions.",
    accept: "Join workspace and get read access", accepting: "Applying access…", failed: "Access could not be applied. Check your account or ask the sender for a new link.",
    scope: "Accepting joins this workspace as an Analyst and grants read access to this database, including its other Articles. Existing higher permissions stay as they are.",
    email: "Signed in as", account: "Use another account", desktop: "Open in DopeDB", download: "Install DopeDB", ready: "Your access is ready",
    steps: "Install DopeDB if needed, sign in to the app with this account, then open the Article below. Keep this page open during installation.",
    local: "To rerun the query, this database also needs your own local credentials or provider login. Shared access never copies the sender’s credentials.",
    managed: "DopeDB obtains your own short-lived database credential when you manually rerun the query.",
    manual: "The link opens the Article. It never runs a query automatically.",
    publicationEyebrow: "Analysis Article",
    publicationResult: "Published HTML",
    publicationDescription: "A published DopeDB Analysis Article.",
    published: "Published",
    unavailableEyebrow: "LINK UNAVAILABLE",
    unavailableTitle: "This shared link is unavailable",
    unavailablePublicBody: "The publication may have been revoked, expired, or never existed. No Article details or saved query were exposed.",
    unexpectedTitle: "This shared link could not be opened",
    unexpectedBody: "The publication was not displayed. Try again, or ask the sender to confirm that sharing is still active.",
    retry: "Try again",
    workspace: "Go to workspace",
  },
  ko: {
    invitation: "아티클 초대", open: "공유 아티클 열기", unavailable: "이 계정으로 사용할 수 없는 링크입니다",
    unavailableBody: "초대받은 이메일로 로그인해 주세요. 초대가 만료·취소되었거나 필요한 권한이 변경되었을 수 있습니다.",
    accept: "워크스페이스 가입하고 읽기 권한 받기", accepting: "권한 적용 중…", failed: "권한을 적용하지 못했습니다. 계정을 확인하거나 보낸 사람에게 새 링크를 요청해 주세요.",
    scope: "수락하면 이 워크스페이스의 분석가로 가입하고, 해당 DB와 그 DB의 다른 아티클을 읽을 수 있습니다. 이미 가진 더 높은 권한은 유지됩니다.",
    email: "로그인 계정", account: "다른 계정 사용", desktop: "DopeDB에서 열기", download: "DopeDB 설치", ready: "읽을 준비가 되었습니다",
    steps: "앱이 없다면 설치한 뒤 이 계정으로 앱에 로그인해 주세요. 이 페이지를 열어 두고, 준비되면 아래 버튼으로 아티클을 여세요.",
    local: "쿼리를 다시 실행하려면 본인의 로컬 DB 자격 증명이나 공급자 로그인이 필요합니다. 보낸 사람의 자격 증명은 전달되지 않습니다.",
    managed: "직접 재조회할 때 본인 전용 단기 DB 자격 증명을 발급받습니다.",
    manual: "링크는 아티클만 엽니다. 쿼리는 자동 실행되지 않습니다.",
    publicationEyebrow: "분석 아티클",
    publicationResult: "게시된 HTML",
    publicationDescription: "DopeDB에서 게시한 분석 아티클입니다.",
    published: "게시",
    unavailableEyebrow: "사용할 수 없는 링크",
    unavailableTitle: "이 공유 링크를 사용할 수 없습니다",
    unavailablePublicBody: "게시가 취소·만료되었거나 존재하지 않을 수 있습니다. 아티클 정보와 저장된 쿼리는 노출하지 않았습니다.",
    unexpectedTitle: "이 공유 링크를 열지 못했습니다",
    unexpectedBody: "게시물을 표시하지 않았습니다. 다시 시도하거나 보낸 사람에게 공유가 유지 중인지 확인해 주세요.",
    retry: "다시 시도",
    workspace: "워크스페이스로 이동",
  },
};
