/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: adc11cc6f2ebbf3cf4e4d5e3575d5c73)
interface __BaseEnv_CloudflareEnv {
	SITE_ANALYTICS: AnalyticsEngineDataset;
	SITE_ANALYTICS_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
