export const analysisManagementText = {
  en: {
    library: "Analysis library",
    refresh: "Refresh",
    loading: "Loading Analysis Articles…",
    loadError: "Could not load the shared Analysis library.",
    detailError: "Could not load this Article's run and publication history.",
    empty: "No Analysis Articles are visible with your current database grants.",
    select: "Select an Analysis Article",
    latestRuns: "Manual run history",
    publications: "Published HTML",
    noRuns: "This saved query has not been run yet.",
    noPublications: "No HTML page has been published.",
    openPublication: "Open published HTML",
    revoked: "Revoked",
    manual: "manual rerun",
    never: "Never",
    openDesktop: "Edit the HTML and run its saved query in DopeDB Desktop.",
    articleHtml: "Article HTML",
    savedDocument: "Saved document",
    savedQuery: "Saved query",
  },
  ko: {
    library: "분석 보관함",
    refresh: "새로고침",
    loading: "분석 아티클을 불러오는 중…",
    loadError: "공유 분석 보관함을 불러오지 못했습니다.",
    detailError: "이 아티클의 실행 및 발행 내역을 불러오지 못했습니다.",
    empty: "현재 DB 권한으로 볼 수 있는 분석 아티클이 없습니다.",
    select: "분석 아티클을 선택하세요",
    latestRuns: "수동 재조회 기록",
    publications: "발행된 HTML",
    noRuns: "아직 이 저장 쿼리를 실행하지 않았습니다.",
    noPublications: "아직 발행된 HTML 페이지가 없습니다.",
    openPublication: "발행된 HTML 열기",
    revoked: "취소됨",
    manual: "수동 재조회",
    never: "없음",
    openDesktop: "HTML 편집과 저장 쿼리 재조회는 DopeDB Desktop에서 수행합니다.",
    articleHtml: "아티클 HTML",
    savedDocument: "저장 문서",
    savedQuery: "저장 쿼리",
  },
} as const;

export type AnalysisManagementText = (typeof analysisManagementText)[keyof typeof analysisManagementText];
